title: Blog Bibliotheks- und Archivinformatik
author: Florian
description: > # this means to ignore newlines
  Lerntagebuch im Kurs Bibliotheks- und Archivinformatik FS2020


show_excerpts: false # set to false to remove excerpts on the homepage
theme: minima
